apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  clusterIP: 10.101.0.1
  selector:
    app: mysql
  ports:
    - nodePort: 30080
      protocol: TCP
      port: 3306
      targetPort: 3306
